
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'leftOPERADORATRIBUICAO IDENTIFICADOR NUMERO OPERADOR\n    expression : IDENTIFICADOR ATRIBUICAO expression\n               | expression OPERADOR expression\n               | IDENTIFICADOR\n               | NUMERO\n    '
    
_lr_action_items = {'IDENTIFICADOR':([0,4,5,],[2,2,2,]),'NUMERO':([0,4,5,],[3,3,3,]),'$end':([1,2,3,6,7,],[0,-3,-4,-2,-1,]),'OPERADOR':([1,2,3,6,7,],[4,-3,-4,-2,4,]),'ATRIBUICAO':([2,],[5,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'expression':([0,4,5,],[1,6,7,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> expression","S'",1,None,None,None),
  ('expression -> IDENTIFICADOR ATRIBUICAO expression','expression',3,'p_expression','analisador.py',42),
  ('expression -> expression OPERADOR expression','expression',3,'p_expression','analisador.py',43),
  ('expression -> IDENTIFICADOR','expression',1,'p_expression','analisador.py',44),
  ('expression -> NUMERO','expression',1,'p_expression','analisador.py',45),
]
